galaxy_info:
  platforms:
    - name: GenericLinux
      versions:
        - all
  author: Mirek DÅ‚ugosz <mirek@mirekdlugosz.com>
  description: Role that installs Kustosz
  license: EUPL-1.2
  min_ansible_version: "1.9"

dependencies:
  - role: system_requirements
